on:
  push: 
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/myarchlinux:latest .
          docker push ghcr.io/${{ github.repository }}/myarchlinux:latest
        working-directory: ./source
      - name: List Package
        id: get-packages
        run: |
          cd source
          packages=$(find . -maxdepth 1 -type d | sed 's|^\./||' | grep -v '^\.' | jq -R . | jq -cs .)
          echo "packages=$packages" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: pre-build
    container:
      image: ghcr.io/${{ github.repository }}/myarchlinux:latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.pre-build.outputs.packages) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Package
        run: |
          chown -R builder .
          chmod +x ./build.sh
          sudo -u builder -- paru -B --noconfirm .
        working-directory: ./source/${{ matrix.dir }}