name: Build Packages
on:
  push: 
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./source
          push: true
          tags: "ghcr.io/${{ github.repository }}/myarchlinux:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
      - name: List Package
        id: get-packages
        run: |
          cd source
          packages=$(find . -maxdepth 1 -type d | sed 's|^\./||' | grep -v '^\.' | jq -R . | jq -cs .)
          echo "packages=$packages" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: pre-build
    container:
      image: ghcr.io/${{ github.repository }}/myarchlinux:latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.pre-build.outputs.packages) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Package Path
        run: |
          echo "PACKAGE_PATH=source/${{ matrix.package }}" >> $GITHUB_ENV
      - name: Build Package
        run: |
          chown -R builder:builder .
          sudo -u builder -- git submodule update --init $PACKAGE_PATH
          pushd $PACKAGE_PATH
          sudo -u builder -- env PKGDEST=$PWD/dist paru -B --noconfirm .
          ls -l dist
          popd
      - name: upload package
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.package }}
          path: ${{ env.PACKAGE_PATH }}/dist/*.pkg.tar.zst
  deploy:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}/myarchlinux:latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: package-*  # Download all packages
          merge-multiple: true
          path: "."
      - name: Update Package Database
        run: |
          repo-add -n -R parrot.db.tar.gz *.pkg.tar.zst
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
