name: Build Packages
on:
  push: 
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./source
          push: true
          tags: "ghcr.io/${{ github.repository }}/myarchlinux:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
      - name: List Package
        id: get-packages
        run: |
          cd source
          packages=$(find . -maxdepth 1 -type d | sed 's|^\./||' | grep -v '^\.' | jq -R . | jq -cs .)
          echo "packages=$packages" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: pre-build
    container:
      image: ghcr.io/${{ github.repository }}/myarchlinux:latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.pre-build.outputs.packages) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Package
        run: |
          chown -R builder:builder .
          sudo -u builder -- git submodule update --init source/${{ matrix.package }}
          cd ./source/${{ matrix.package }}
          sudo -u builder -- env PKGDEST=$PWD/dist paru -B --noconfirm .
          ls -l dist
      - name: upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ./dist/*.pkg.tar.zst