on:
  push: 
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List Package
        id: get-packages
        run: |
          cd source
          packages=$(find . -maxdepth 1 -type d | sed 's|^\./||' | grep -v '^\.' | jq -R . | jq -cs .)
          echo "packages=$packages" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://archlinux:base-devel
    needs: pre-build
    strategy:
      matrix:
        dir: ${{ fromJson(needs.pre-build.outputs.packages) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update Packages and Create User
        run: |
          chmod +x ./setup.sh
          ./setup.sh
        working-directory: ./source
      - name: Build Package
        run: |
          chmod +x ./build.sh
          sudo -u builder -- ./build.sh ${{ matrix.dir }}
        working-directory: ./source